language: ruby
install: bundle install
script:
- bundle exec jekyll build --config _config.yml
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ] && [ $TRAVIS_BRANCH = 'source' ]; then
  chmod +x ./scripts/deploy;
  source scripts/deploy;
  fi;
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - GITHUB_REPO=github.com/Vinatorul/vinatorul.github.io.git
  - REPO_TARGET_BRANCH=master
sudo: false
